### ISSUE TITLE
Dockerfile in docker folder

### ISSUE THREAD

**Issue by ericjvandervelden** [devfile-samples/devfile-sample-java-springboot-basic#12]
Where is it documented that the Dockerfile must be in a docker folder? Indeed, otherwise s2i in openshift does not work.

**Comment by michael-valdron** [comment]
Hi @ericjvandervelden,

Thank you for your issue report.

Due to the age of this issue I'm going to close. However, if you would like to re-open, please feel free to [create followup issue(s)](https://github.com/devfile/api/issues/new/choose) for this under [devfile/api](https://github.com/devfile/api) so we can follow up as we don't usually monitor issues created under this repository. 

See our [contributing guide](https://github.com/devfile/api/blob/main/CONTRIBUTING.md) for more information about contributing and how to contact us.
